name: Build release artifact
on:
  release:
    types: [published, created, edited]

jobs:
  setup-build-env:
    uses: strevol-mpi-mis/rafft-rs/.github/workflows/setup-build-env.yml@main
    
  build:
    runs-on: [ubuntu-latest]
    needs: setup-build-env
    env:
      CPATH: ${{ needs.setup-build-env.outputs.conda_prefix }}/include
      LIBRNA_INCLUDE_DIR: ${{ needs.setup-build-env.outputs.conda_prefix }}/include
      LIBRNA_LIB_DIR: ${{ needs.setup-build-env.outputs.conda_prefix }}/lib
    
    steps:
      - uses: actions/checkout@v2
      - run: cargo build --features bindings --release
