name: CI checks
on: [push]

jobs:
  setup-build-env:
    uses: strevol-mpi-mis/rafft-rs/.github/workflows/setup-build-env.yml@gh-actions
    
  check:
    runs-on: ubuntu-latest
    needs: setup-build-env
    env:
      CPATH: ${{ needs.setup-build-env.outputs.conda_prefix }}/include
      LIBRNA_INCLUDE_DIR: ${{ needs.setup-build-env.outputs.conda_prefix }}/include
      LIBRNA_LIB_DIR: ${{ needs.setup-build-env.outputs.conda_prefix }}/lib
    
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildrafft
      - name: Run clippy
        shell: bash -l {0}
        run: cargo clippy --verbose
      - name: Run tests
        shell: bash -l {0}
        run: cargo test --verbose
