name: CI checks
on: [push]

jobs:
  setup-build-env:
    uses: strevol-mpi-mis/rafft-rs/.github/workflows/setup-build-env.yml@gh-actions
    
  check:
    runs-on: ubuntu-latest
    needs: setup-build-env
    env:
      CPATH: ${{ needs.setup-build-env.outputs.cpath }}
    
    steps:
      - name: Run clippy
        run: cargo clippy --features librna-sys/auto
      - name: Run tests
        run: cargo test --features librna-sys/auto
