name: Setup build environment
on:
  workflow_call:
    outputs:
      cpath:
        description: "The C header file directory of the created conda environment"
        value: ${{ jobs.install-viennarna.outputs.cpath }}
  
jobs:
  install-viennarna:
    name: Install ViennaRNA
    runs-on: [ubuntu-latest]
    outputs:
      cpath: $${{ steps.out.outputs.cpath }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda packages
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{env.CACHE_NUMBER}}-${{ hashFiles('.github/build_env.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: buildrafft
          channel-priority: strict
          environment-file: .github/build_env.yml
          use-only-tar-bz2: true
      - id: out
        shell: bash -l {0}
        run: echo "::set-output name=cpath::$CONDA_PREFIX/include"
